### ISSUE TITLE
Uncaught (in promise) TypeError: string is undefined

### ISSUE THREAD

**Issue by janpio** [joshua-shone/n26#1]
Hey Josh, nice app!

Tried to use it with my CSV and get a crash though:

Firefox:
```
Uncaught (in promise) TypeError: string is undefined
    dateStringToTimestampMs https://shone.dev/cashtable/main.js:183
    timestamps https://shone.dev/cashtable/main.js:149
    loadCsvString https://shone.dev/cashtable/main.js:149
    loadCsvFile https://shone.dev/cashtable/main.js:105
    onchange https://shone.dev/cashtable/main.js:18
    EventHandlerNonNull* https://shone.dev/cashtable/main.js:15
[main.js:183:30](https://shone.dev/cashtable/main.js)
    onchange https://shone.dev/cashtable/main.js:20
    AsyncFunctionThrow self-hosted:811
    (Async: async)
    <anonym> https://shone.dev/cashtable/main.js:15
```

Chrome slightly different error:
```
main.js:183 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at dateStringToTimestampMs (main.js:183:37)
    at main.js:149:48
    at Array.map (<anonymous>)
    at loadCsvString (main.js:149:29)
    at loadCsvFile (main.js:105:9)
    at async fileInput.onchange (main.js:18:5)
```

Here is one of the CSVs I tried:
```
"Datum","Empfänger","Kontonummer","Transaktionstyp","Verwendungszweck","Betrag (EUR)","Betrag (Fremdwährung)","Fremdwährung","Wechselkurs"
"2023-01-20","PayPal Europe S.a.r.l. et Cie S.C.A","LU89751000135104200E","Lastschrift","1024763190893 PP.5068.PP . Spotify AB, Ihr Einkauf bei Spotify AB","-12.99","","",""
"2023-01-21","Zeit fuer Brot","","MasterCard Zahlung","-","-8.7","-8.7","EUR","1.0"
"2023-01-21","Flink SE","","MasterCard Zahlung","","-133.89","-133.89","EUR","1.0"
```
 (Only this month's data, so should be easy to debug)

**Comment by janpio** [comment]
And worked around that by switching my N26 UI to English, which also creates a CSV with english column names:
```
"Date","Payee","Account number","Transaction type","Payment reference","Amount (EUR)","Amount (Foreign Currency)","Type Foreign Currency","Exchange Rate"
...
```

Easiest fix would to add that step to the instructions I guess 😆

**Comment by shone** [comment]
Hi @janpio, thanks for the detailed feedback! It's been fixed now so that non-English CSV files can be opened directly, at least for the currently supported languages (English, German, French, Spanish and Italian).

Some future improvements could include nicer error feedback and support for showing the cashtable app itself in different languages. Some work needs to be done to make the graph look right for your example CSV too :sweat_smile:
